import Head from 'next/head';
import{BsFillMoonStarsFill} from 'react-icons/bs';
import
{AiFillTwitterCircle,
   AiFillLinkedin,
   AiFillAndroid, 
  AiFillGithub,
  AiOutlineMail,
AiFillHtml5,
DiReact,
SiJavascript,
SiTailwindcss,
DiCss3,
FaBootstrap,
BiGitMerge,
SiTypescript,
SiMysql,
SiExpress,
SiMongodb,
FaNodeJs
} 
   from 'react-icons/ai';
import myImage from '../public/design.jpg'
<styles />
export default function Home() {
  return (
    <div >
      <Head>
        <title>Luke Sorrenti Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
   <section className='min-h-screen'>
<nav className='py-10 mb-12 flex justify-between'>
  <h1 className='text-xl font-burtons'>
    Developed by Luke
  </h1>
  <ul className='flex items-center'>
    <li>
<BsFillMoonStarsFill className='cursor-pointer text-2xl' />
    </li>
    <li className=''>
      <a className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"href="">Resume</a>
    </li>
  </ul>
</nav>
    <div className='text-center p-10'>
      <h2 className='text-5xl py-2 text-teal-600 font-medium'>Luke Sorrenti</h2>
      <h3 className='text-2xl py-2'>
        Developer & Designer
      </h3>
      <p className='text-medium py-5 leading-8 text-gray-800'>
        Freelancer providing services for programming and design 
        content needs, join me down below to connect!!
      </p>
    </div>
    <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 '>
<AiFillTwitterCircle />
  <AiFillLinkedin />
  <AiFillAndroid />
  <AiFillGithub />
  <AiOutlineMail/>
    </div>
    <div className="relative bg-gradient-to-b
     from-teal-500 rounded-full w-80 h-80 mt-20
     mx-auto overflow-hidden" layout="fill" objectFit="cover">
    </div>
   </section>
  <section>
    <div>
      <h3 className='3xl py-1'>
        Services I offer
      </h3>
      <p className='text-md py-2 leading-8 text-gray-800'>
        Since the beginning of my learning journey, I've been 
        eager to <span className="text-teal-500">build and design websites</span> Here are the technologies 
        I'm proficient in
      </p>
    </div>
    <div>
      <div>
      <h3>
        
        Modern Designs
      </h3>
      
      <p>
        Creating clean and elegant designs tailored to your 
        specifications
      </p>
      </div>
    </div>
  </section>

      </main>

    
    </div>
  );
}
